### PR TITLE
#164198149 Implements view and post comments for an article

### PR DESCRIPTION
**Pull request by valenstical**
#### What does this PR do?
This PR adds a feature that allows users to view and post comments for a specific article page.

#### Description of Task to be completed

- [x] Write unit test
- [x] Create CommentBox component to display a single comment
- [x] Create Comments component to group all comments related components
- [x] Create component for user to post comments
- [x] Create relevant actions and reducers for component
- [x] Consume API endpoint to read comments
- [x] Consume API endpoint to post comment
- [x] Write integration tests

#### How should this be manually tested

1. Clone repo by running the following command on your terminal:

```bash
git clone -b feature/164198149/comments-on-articles--single-branch \
https://github.com/andela/apollo-ah-frontend.git
```

2. Navigate into the repo directory: `cd apollo-ah-frontend`

2. Install dependency packages with: `npm install`

3. On the root directory, create a `.env` file from `.env.example` and provide required credentials

4. Run `npm test`

#### What are the relevant pivotal tracker stories

[#164198149](https://www.pivotaltracker.com/story/show/164198149)

#### Screenshots
ezgif-1-33d707af1f38

### CODE REVIEW

**Review by aanchirinah — APPROVED** [review]
LGTM , great job @valenstical

**Comment by aanchirinah** [comment]
@valenstical Also resolve conflicts

**Review by thislekan — APPROVED** [review]
LGTM

**Review by devdbrandy — APPROVED** [review]
:sparkles: :sparkles: Looks good :+1: :sparkles: :sparkles:

**Pull request merged**
