### PR TITLE
#165605023 Implements feedback from PO

### PR DESCRIPTION
**Pull request by valenstical**
#### What does this PR do?
This PR implements a feature that adds a user dashboard page to the application with statistics about the author's articles.

#### Description of Task to be completed

- [x] Write unit test
- [x] add carousel for categories
- [x] add dynamic header for login page (Hide unnecessary details in the navbar on login page)
- [x] make search in navbar redirect to search page after user inputs a search term

#### How should this be manually tested

1. Clone repo by running the following command on your terminal:

```bash
git clone -b feature/165605023/implement-feedback--single-branch \
https://github.com/andela/apollo-ah-frontend.git
```

2. Navigate into the repo directory: `cd apollo-ah-frontend`

2. Install dependency packages with: `npm install`

3. On the root directory, create a `.env` file from `.env.example` and provide required credentials

4. Run `npm test`

#### Any background context you want to provide
N/A

#### What are the relevant pivotal tracker stories

[#165605023](https://www.pivotaltracker.com/story/show/165605023)

#### Screenshots
ezgif-2-1b0c611a2a51

### CODE REVIEW

**Review by aanchirinah — APPROVED** [review]
LGTM

**Comment by aanchirinah** [comment]
@valenstical , You have merge conflicts

**Comment by valenstical** [comment]
Hello @aanchirinah, I have fixed the merge conflicts.

**Review by fejiroofficial — APPROVED** [review]
Nice job! LGTM

**Pull request merged**
